server:
  port: 9010
document:
  windowsFileTempLoc: d:/v2file/
  linuxFileTempLoc: /home/ecm/v2file/
mch:
  name: mch
  version: 3.8
  copyrightYear: 2018
  ssl_type: https://
  #base_url: 172.20.10.3:8088/admin/
  base_url: www.vvvpure.com:8088/admin/
  defaultBaseDir: /static/v2file/
  isroot_dir: /static/file_upload/
  picDir: /static/v2file/pic/
  avat_dir: /home/ecm/avat/
  email_smtp: smtp.exmail.qq.com
  email_port: 465
  email_account: wjy_sys@vvvpure.com
  sendername: sysmessage
  email_password: W1j2y3x4y5
  demoEnabled: false
  rollVerification: true
  isstatic: N
#腾讯云配置
tencent:
  appId: 1400454235
  # 腾讯云的SecretId（永久的，可在控制台开启或关闭）
  secretId: AKIDGJOxKVR5bCYfW883hHWXHlmZ5KbmN9RV
  # 腾讯云的SecretKey（永久的，可在控制台开启或关闭）
  secretKey: lHWfavNddZIlxIWZNvDtJafWMwHMONCl
  # 腾讯云的allowPrefix(允许上传的路径)
  allowPrefix: '*'
  # 腾讯云的访问基础链接:
  baseUrl: https://ithink-1303188565.cos.ap-shanghai.myqcloud.com
  # 腾讯云的cdn访问链接:
  cdnUrl: https://vvvpure.com
  # 腾讯云的bucket (存储桶)
  bucket: ithink-1303188565
  # 腾讯云的临时密钥时长(单位秒)
  durationSeconds: 1800
  # 腾讯云的region(bucket所在地区)
  region: ap-shanghai
  
spring:
  application:
    name: e-commerce-admin
    #引入其他配置文件，例如ftpHX 未配置文件application-ftpHX.yml
    #include: ftpHX,ftpCloud
  servlet:
    multipart:
      #设置总上传的数据大小
      max-request-size: 100MB
      #单个文件大小
      maxFileSize : 30MB
        #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     druid:
#       master:
    url: jdbc:mysql://81.68.128.124:3306/jiche_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: shopadm
    password: W1j2y3x4y5.
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    max-active: 50
    min-idle: 10
    max-wait: 5000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 20000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
  redis:
    host: 81.68.128.124 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 1qaz2wsx # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 你的Eureka Server地址
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath*:mapper/*.xml

value:
  zuul-uri: "http://localhost:9000"

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /static/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /log/generateValidateCode
      - /index

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: e-commerce-admin #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头
